const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const http = require('node:http');
const root = path.resolve(__dirname, '..');
(async () => {
 const output = path.join(root, 'test-output');
 await fs.mkdir(output,{recursive:true});
 const userData = await fs.mkdtemp(path.join(output,'settings-ui-'));
 const server = http.createServer((req,res)=>{ res.writeHead(200,{'content-type':'application/json'}); res.end(JSON.stringify(req.url.includes('/api/tags')?{models:[{name:'test-autocomplete'},{name:'test-cheap'}]}:{data:[{id:'test-api-model'}]})); });
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const baseUrl='http://127.0.0.1:'+server.address().port;
 const {defaults}=require('../electron/preferences.cjs');
 await fs.writeFile(path.join(userData,'settings.json'),JSON.stringify({...defaults,provider:'ollama',baseUrl,model:'test-autocomplete',nativeLanguage:'',taskProfiles:{},keys:{}}));
 const env={...process.env,WRAITER_USER_DATA:userData}; delete env.ELECTRON_RUN_AS_NODE;
 let app;
 try {
  app=await electron.launch({args:[root],env,timeout:60000});
  const page=await app.firstWindow();
  const failures=[]; page.on('pageerror',error=>failures.push(error.message));
  await page.getByRole('textbox',{name:'Manuscript editor',exact:true}).waitFor({timeout:30000});
  await page.screenshot({path:path.join(output,'writer-desktop-light.png')});
  await page.getByRole('combobox',{name:'Font family',exact:true}).click();
  await page.getByRole('listbox',{name:'Fonts',exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'writer-font-picker.png')});
  await page.getByRole('textbox',{name:'Search fonts',exact:true}).press('Escape');
  const command=async name=>app.evaluate(({BrowserWindow},value)=>BrowserWindow.getAllWindows()[0].webContents.send('command',value),name);
  const nativePress=async (keyCode,modifiers=[])=>app.evaluate(({BrowserWindow},{keyCode,modifiers})=>{const contents=BrowserWindow.getAllWindows()[0].webContents;contents.sendInputEvent({type:'keyDown',keyCode,modifiers});contents.sendInputEvent({type:'keyUp',keyCode,modifiers});},{keyCode,modifiers});
  await command('settings-language');
  await page.getByRole('combobox',{name:'Native language',exact:true}).selectOption('sv-SE');
  await page.getByRole('combobox',{name:'Default document language',exact:true}).selectOption('en-GB');
  await page.getByRole('tab',{name:'Connections',exact:true}).click();
  await page.getByRole('status').filter({hasText:/models available/}).waitFor();
  await page.getByRole('combobox',{name:'Spell correction model',exact:true}).fill('test-cheap');
  await page.screenshot({path:path.join(output,'writer-task-models.png')});
  await page.getByRole('tab',{name:'Writing AI',exact:true}).click();
  await page.getByRole('checkbox',{name:'Enable AI writing assistance',exact:true}).check();
  await page.getByRole('spinbutton',{name:'Suggestion length (words)',exact:true}).fill('60');
  await page.getByRole('tab',{name:'Shortcuts',exact:true}).click();
  const capture=page.getByRole('button',{name:'Shortcut for Correct selection',exact:true});
  await capture.click(); await capture.press('F8');
  assert.match(await capture.innerText(),/F8/);
  await capture.click(); await page.waitForFunction(()=>document.querySelector('.hotkey-capture.capturing')); await nativePress('S',['control']);
  await page.waitForFunction(()=>document.querySelector('.hotkey-capture[aria-label="Shortcut for Correct selection"]').textContent.includes('S'));
  assert.ok(await page.getByRole('button',{name:'Save settings',exact:true}).isDisabled());
  assert.match(await page.getByRole('alert').innerText(),/Correct selection and Save|Save and Correct selection/);
  await capture.click(); await page.waitForFunction(()=>document.querySelector('.hotkey-capture.capturing')); await nativePress('O',['control']);
  await page.waitForFunction(()=>document.querySelector('.hotkey-capture[aria-label="Shortcut for Correct selection"]').textContent.includes('O'));
  assert.match(await capture.innerText(),/Ctrl.*O/);
  assert.ok(await page.getByRole('button',{name:'Save settings',exact:true}).isDisabled());
  await capture.click(); await capture.press('F8');
  await page.screenshot({path:path.join(output,'writer-shortcuts.png')});
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByRole('heading',{name:'Settings',exact:true}).waitFor({state:'hidden'});
  const saved=JSON.parse(await fs.readFile(path.join(userData,'settings.json'),'utf8'));
  assert.equal(saved.nativeLanguage,'sv-SE'); assert.equal(saved.language,'en-GB');
  assert.equal(saved.taskProfiles.correct.model,'test-cheap'); assert.equal(saved.taskProfiles.continue.model,'test-autocomplete');
  assert.equal(saved.hotkeys.correct,'F8'); assert.equal(saved.predictionWords,60); assert.equal(saved.enabled,true);
  await command('settings-appearance');
  await page.getByRole('button',{name:'Dark',exact:true}).click();
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.sidebar-nav')).color==='rgb(232, 233, 237)');
  await page.screenshot({path:path.join(output,'writer-desktop-dark.png')});
  await command('settings-appearance');
  await page.getByRole('button',{name:'High contrast',exact:true}).click();
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='contrast');
  await page.screenshot({path:path.join(output,'writer-desktop-contrast.png')});
  assert.deepEqual(failures,[]);
  console.log('PASS: native menu settings, task-specific models, native language, AI settings, shortcut capture/conflicts, and all themes. Screenshots saved in test-output.');
 } finally { if(app) { await app.evaluate(({app})=>app.exit(0)).catch(()=>{}); await app.close().catch(()=>{}); } server.closeAllConnections(); await new Promise(resolve=>server.close(resolve)); }
})().catch(error=>{console.error(error);process.exitCode=1;});
