// Synthetic documents and isolated application data. Model-download dialogs use
// deterministic IPC responses; the engine and GGUF workflows have live QA too.
const { _electron } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const http = require('node:http');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const waitFor = async (fn, message, timeout=25000) => { const end=Date.now()+timeout; while(Date.now()<end) { try {if(await fn())return}catch{} await new Promise(resolve=>setTimeout(resolve,150)); }throw new Error(message) };
const p = text => ({type:'paragraph',...(text?{content:[{type:'text',text,marks:[{type:'bold'}]}]}:{})});
const fixture = {format:'wraiter',version:1,id:'v04-test',title:'Local model and paragraph test',chapters:[{id:'one',title:'Opening',content:{type:'doc',content:[p('Keep the first paragraph.'),p(),p('  '),p('Keep the ending.')] }},{id:'two',title:'Later',content:{type:'doc',content:[p(),p('Second chapter text.')]}}],notes:'',style:'',references:[],snapshots:[]};
(async()=>{
 const output=path.join(root,'test-output');await fs.mkdir(output,{recursive:true});const userData=await fs.mkdtemp(path.join(output,'v04-ui-')),errors=[],checks=[];
 const server=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET')return res.end('{"models":[{"name":"mock-agent"}]}');let body='';for await(const chunk of req)body+=chunk;const request=JSON.parse(body);const prompt=request.prompt||request.messages?.map(item=>item.content).join('\n')||'';const done=prompt.includes('"tool":"remove_empty_paragraphs"');const answer=JSON.stringify({message:done?'Removed 3 empty paragraphs across both chapters.':'Removing empty paragraphs.',done,tools:done?[]:[{name:'remove_empty_paragraphs',arguments:{}}]});res.end(JSON.stringify({response:answer,message:{content:JSON.stringify({completion:answer})}}));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 await fs.writeFile(path.join(userData,'settings.json'),JSON.stringify({provider:'ollama',baseUrl:`http://127.0.0.1:${server.address().port}`,model:'mock-agent',ollamaMode:'raw',enabled:true,continuous:false,taskProfiles:{chat:{provider:'ollama',baseUrl:`http://127.0.0.1:${server.address().port}`,model:'mock-agent'}},keys:{}}));await fs.writeFile(path.join(userData,'recovery.json'),JSON.stringify({project:fixture,path:null,expectedHash:null}));
 const models=path.join(userData,'Test models'),manifest=path.join(models,'manifests','registry.ollama.ai','library','test-writer','tiny'),digest='a'.repeat(64);
 await fs.mkdir(path.dirname(manifest),{recursive:true});await fs.mkdir(path.join(models,'blobs'),{recursive:true});await fs.writeFile(path.join(models,'blobs','sha256-'+digest),'synthetic');await fs.writeFile(manifest,JSON.stringify({layers:[{digest:'sha256:'+digest,size:9,mediaType:'application/vnd.ollama.image.model'}]}));
 const env={...process.env,WRAITER_USER_DATA:userData};delete env.ELECTRON_RUN_AS_NODE;
 const options=process.env.WRAITER_EXECUTABLE?{executablePath:process.env.WRAITER_EXECUTABLE,args:[],env,timeout:60000}:{args:[root],env,timeout:60000};let app,page;
 const launch=async()=>{app=await _electron.launch(options);page=await app.firstWindow();page.on('pageerror',error=>errors.push(error.message));await page.getByRole('textbox',{name:'Manuscript editor',exact:true}).waitFor({timeout:30000})};
 const command=async value=>app.evaluate(({BrowserWindow},value)=>BrowserWindow.getAllWindows()[0].webContents.send('command',value),value);
 const recover=async()=>JSON.parse(await fs.readFile(path.join(userData,'recovery.json'),'utf8')).project;
 try{
  await launch();await command('toggle-assistant');await page.getByRole('textbox',{name:'Ask the writing assistant'}).fill('Remove empty lines then');await page.getByRole('button',{name:'Send writing question'}).click();await waitFor(async()=> (await recover()).chapters[0].content.content.length===2,'Agent did not remove paragraph blocks');
  let saved=await recover();assert.equal(saved.chapters[1].content.content.length,1);assert.equal(saved.chapters[0].content.content[0].content[0].marks[0].type,'bold');await page.screenshot({path:path.join(output,'v04-empty-paragraphs.png')});
  await command('undo');await waitFor(async()=> (await recover()).chapters[0].content.content.length===4,'Agent undo did not restore blank paragraphs');await app.close();await launch();await command('redo');await waitFor(async()=> (await recover()).chapters[0].content.content.length===2,'Agent redo failed after restart');checks.push('Screenshot request removes actual empty paragraphs across chapters, preserves marks, and undoes/redoes across restart.');
  await command('settings-local');await page.getByRole('tab',{name:'Local models',exact:true}).waitFor();await page.getByText('Engine and model storage',{exact:true}).click();await page.getByRole('textbox',{name:'Local model folder'}).waitFor();
  await app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]})},models);await page.getByRole('button',{name:'Choose folder',exact:true}).click();await waitFor(async()=>await page.getByRole('textbox',{name:'Local model folder'}).inputValue()===models,'Custom model folder did not apply');
  await page.getByRole('combobox',{name:'Local model task',exact:true}).selectOption('continue');await page.getByRole('button',{name:'Use model',exact:true}).click();await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.getByRole('dialog',{name:'Settings',exact:true}).waitFor({state:'hidden'});let prefs=await page.evaluate(()=>window.wraiter.boot());assert.equal(prefs.prefs.taskProfiles.continue.provider,'local');assert.equal(prefs.prefs.taskProfiles.continue.model,'test-writer:tiny');assert.equal(prefs.prefs.taskProfiles.chat.provider,'ollama');checks.push('Custom Ollama folders are discovered offline; local model assignment persists independently for each task.');
  await command('settings-local');await page.getByText('Memory and acceleration',{exact:true}).click();await page.getByRole('combobox',{name:'Local acceleration'}).selectOption('cpu');await page.getByRole('combobox',{name:'Local context size'}).selectOption('4096');await page.getByRole('combobox',{name:'Local unload delay'}).selectOption('1');await page.getByRole('combobox',{name:'Local loaded model limit'}).selectOption('2');await page.getByRole('button',{name:'Apply resource settings'}).click();await waitFor(async()=> (await page.evaluate(()=>window.wraiter.localStatus())).config.contextLength===4096,'Resources did not save');await page.screenshot({path:path.join(output,'v04-local-models.png')});
  await page.getByRole('button',{name:'Start engine',exact:true}).click();await page.getByRole('button',{name:'Stop engine',exact:true}).waitFor({timeout:40000});await page.getByRole('button',{name:'Stop engine',exact:true}).click();await page.getByRole('button',{name:'Start engine',exact:true}).waitFor();checks.push('Resource settings persist, and WRAITER starts and stops its own installed engine.');
  const gguf=path.join(userData,'Chosen model.gguf'),data=Buffer.alloc(40);data.write('GGUF');data.writeUInt32LE(3,4);await fs.writeFile(gguf,data);
  await page.getByRole('tab',{name:'Add GGUF file',exact:true}).click();await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},gguf);await page.getByRole('button',{name:'Choose GGUF file',exact:true}).click();await page.getByRole('textbox',{name:'Imported local model name'}).waitFor();assert.equal(await page.getByRole('textbox',{name:'Imported local model name'}).inputValue(),'chosen-model');
  await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('local:import');ipcMain.handle('local:import',(_event,token,name)=>{if(typeof token!=='string'||name!=='chosen-model')throw new Error('Unexpected file registration');return {success:true}})});await page.getByRole('button',{name:'Add model',exact:true}).click();await waitFor(async()=>await page.getByRole('tab',{name:/On this computer/}).getAttribute('aria-selected')==='true','Import did not return to installed models');assert.deepEqual(await fs.readFile(gguf),data);checks.push('GGUF chooser validates the selected file, supplies a reusable model name, and preserves source bytes.');
  await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('local:catalog-info');ipcMain.handle('local:catalog-info',(_event,name)=>({name,bytes:512*1024**2}));ipcMain.removeHandler('local:pull');ipcMain.handle('local:pull',()=>({success:true}));ipcMain.removeHandler('local:release');ipcMain.handle('local:release',()=>({version:'v0.34.0',bytes:1469375054}));ipcMain.removeHandler('local:install');ipcMain.handle('local:install',()=>({success:true}))});
  await page.getByRole('tab',{name:'Download models',exact:true}).click();await page.getByRole('button',{name:'Check download',exact:true}).click();await page.getByRole('button',{name:'Download model',exact:true}).click();await waitFor(async()=>await page.getByRole('tab',{name:/On this computer/}).getAttribute('aria-selected')==='true','Download did not return to models');await page.getByText('Engine and model storage',{exact:true}).click();await page.getByRole('button',{name:'Check engine download'}).click();await page.getByRole('button',{name:/Install v0.34.0/}).click();checks.push('Download and portable-runtime setup show the checked package size before starting the requested operation.');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.getByRole('dialog',{name:'Settings',exact:true}).waitFor({state:'hidden'});await app.close();await launch();const status=await page.evaluate(()=>window.wraiter.localStatus());assert.equal(status.modelDirectory,models);assert.equal(status.config.gpu,'cpu');assert.equal(status.config.contextLength,4096);assert.equal(status.config.idleMinutes,1);assert.equal(status.config.maxLoaded,2);assert.equal(status.running,false);assert.deepEqual(errors,[]);checks.push('Local storage, resource settings and task assignments survive restart without starting a model automatically.');
  const report={passed:true,checks,userData};await fs.writeFile(path.join(output,'v04-app-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }catch(error){console.error(error);await page?.screenshot({path:path.join(output,'v04-ui-failure.png')}).catch(()=>{});throw error}finally{if(page)await page.getByRole('button',{name:'Close WRAITER',exact:true}).click({timeout:1000}).catch(()=>{});await app?.close().catch(()=>{});await new Promise(resolve=>server.close(resolve))}
})().catch(error=>{console.error(error);process.exitCode=1});
