const { _electron } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const http = require('node:http');
const assert = require('node:assert/strict');
const waitFor = async (fn,label) => { const end=Date.now()+20000;while(Date.now()<end){if(await fn())return;await new Promise(r=>setTimeout(r,100))}throw new Error(label) };
(async()=>{
 const root=path.resolve(__dirname,'..'),output=path.join(root,'test-output'),userData=await fs.mkdtemp(path.join(output,'v05-ui-'));const checks=[],errors=[],requests=[];
 const sentence='The winds shifted in the evening air. As the day came to an end and the ground cooled, the uppåtvindar that had carried her weakened.';
 const para=text=>({type:'paragraph',content:[{type:'text',text}]});
 const fixture={format:'wraiter',version:1,id:'v05-'+Date.now(),title:'Page and rephrasing test',language:'en-US',documentStyle:{fontFamily:'Cambria',fontSize:12,lineHeight:1.5},chapters:[{id:'one',title:'Opening',status:'Draft',content:{type:'doc',content:[para(sentence),...Array.from({length:35},(_,i)=>para(`Paragraph ${i+1}. `+'The quiet garden carried the warmth of the afternoon. '.repeat(6))),para('Long paragraph. '+'A long paragraph continues across a page without becoming separate paragraphs. '.repeat(60)),para('The last line.')]}}]};
 const server=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET')return res.end('{"models":[{"name":"test-rewriter"}]}');let source='';for await(const chunk of req)source+=chunk;const request=JSON.parse(source);requests.push(request);const answer=JSON.stringify({alternatives:[{text:'updrafts',rating:3},{text:'rising air currents',rating:2},{text:'upward-moving air',rating:1}]});res.end(JSON.stringify({response:answer,message:{content:JSON.stringify({completion:answer})}}))});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 await fs.writeFile(path.join(userData,'settings.json'),JSON.stringify({setupComplete:true,tutorialComplete:true,provider:'ollama',baseUrl:`http://127.0.0.1:${server.address().port}`,model:'test-rewriter',ollamaMode:'guided',enabled:true,continuous:false,nativeLanguage:'sv-SE',keys:{}}));await fs.writeFile(path.join(userData,'recovery.json'),JSON.stringify({project:fixture,path:null,expectedHash:null}));
 const env={...process.env,WRAITER_USER_DATA:userData};delete env.ELECTRON_RUN_AS_NODE;let app,page,editor;
 const options=process.env.WRAITER_EXECUTABLE?{executablePath:process.env.WRAITER_EXECUTABLE,args:[],env,timeout:60000}:{args:[root],env,timeout:60000};
 const launch=async()=>{app=await _electron.launch(options);page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));editor=page.getByRole('textbox',{name:'Manuscript editor',exact:true});await editor.waitFor({timeout:30000})};
 const command=async name=>app.evaluate(({BrowserWindow},name)=>BrowserWindow.getAllWindows()[0].webContents.send('command',name),name);
 const recover=async()=>JSON.parse(await fs.readFile(path.join(userData,'recovery.json'),'utf8')).project;
 const select=async text=>{await editor.evaluate((element,text)=>{element.focus();const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const i=walker.currentNode.textContent.indexOf(text);if(i>=0){const range=document.createRange();range.setStart(walker.currentNode,i);range.setEnd(walker.currentNode,i+text.length);const s=window.getSelection();s.removeAllRanges();s.addRange(range);document.dispatchEvent(new Event('selectionchange'));return}}throw new Error('Selection missing')},text);await page.waitForTimeout(120)};
 try{
  await launch();assert.ok(await page.getByRole('button',{name:'Continuous view',exact:true}).isVisible());
  const tail=await page.locator('.writing-scroll').evaluate(el=>{el.scrollTop=el.scrollHeight;const last=el.querySelector('.manuscript p:last-child').getBoundingClientRect(),bounds=el.getBoundingClientRect();return {below:bounds.bottom-last.bottom,height:bounds.height}});assert.ok(tail.below>tail.height*.65,JSON.stringify(tail));checks.push('Continuous view is the default and scrolls almost one viewport below the last line.');
  await command('settings-appearance');await page.getByRole('combobox',{name:'Document view',exact:true}).selectOption('pages');await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.getByRole('dialog',{name:'Settings',exact:true}).waitFor({state:'hidden'});await waitFor(async()=>await page.locator('.page-card').count()>2,'Pages not created');
  const originalCount=fixture.chapters[0].content.content.length;assert.equal((await recover()).chapters[0].content.content.length,originalCount);
  await page.locator('.writing-scroll').evaluate(el=>el.scrollTop=800);await page.screenshot({path:path.join(output,'v05-divided-pages.png')});
  const pageGeometry=()=>{
   const cards=[...document.querySelectorAll('.page-card')].map(el=>{const r=el.getBoundingClientRect();return {top:r.top,bottom:r.bottom}}),dom=document.querySelector('.manuscript');let crossing=0,count=0;const walker=document.createTreeWalker(dom,NodeFilter.SHOW_TEXT);
   while(walker.nextNode()){if(walker.currentNode.parentElement.closest('.pagination-spacer'))continue;const range=document.createRange();range.selectNodeContents(walker.currentNode);for(const r of range.getClientRects()){if(!r.width)continue;count++;if(!cards.some(p=>r.top>=p.top+20&&r.bottom<=p.bottom-20))crossing++}}
   return {crossing,count,pages:cards.length,gaps:document.querySelectorAll('.pagination-spacer').length}
  };const flow=await page.evaluate(pageGeometry);console.log('Page geometry:',flow);assert.equal(flow.crossing,0,'Text crosses page gaps');checks.push('Divided pages automatically flow wrapped paragraphs without changing document nodes.');await page.getByRole('combobox',{name:'Document zoom',exact:true}).selectOption('150');await page.waitForTimeout(350);const zoomFlow=await page.evaluate(pageGeometry);assert.equal(zoomFlow.crossing,0,'Text crosses page gaps at 150% zoom');await page.getByRole('combobox',{name:'Document zoom',exact:true}).selectOption('100');await page.waitForTimeout(200);
  await editor.click();await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.focus();w.webContents.sendInputEvent({type:'keyDown',keyCode:'End',modifiers:['control']});w.webContents.sendInputEvent({type:'keyUp',keyCode:'End',modifiers:['control']})});await page.waitForTimeout(150);assert.ok(await editor.evaluate(element=>element.lastElementChild.contains(window.getSelection().anchorNode)), 'Native Ctrl+End did not reach the document end');await select('The last line.');await page.evaluate(()=>{const selection=window.getSelection();selection.collapseToEnd();document.dispatchEvent(new Event('selectionchange'))});await page.waitForTimeout(100);await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.focus();w.webContents.sendInputEvent({type:'keyDown',keyCode:'Enter',modifiers:['control']});w.webContents.sendInputEvent({type:'keyUp',keyCode:'Enter',modifiers:['control']})});await page.waitForTimeout(150);await page.keyboard.insertText('A new manual page.');await waitFor(async()=>JSON.stringify(await recover()).includes('A new manual page.'),'Manual break typing not saved');let saved=await recover();assert.ok(saved.chapters[0].content.content.at(-1).attrs.pageBreakBefore);await command('undo');await waitFor(async()=>!JSON.stringify(await recover()).includes('A new manual page.'),'Typing undo failed');await command('undo');await waitFor(async()=>!(await recover()).chapters[0].content.content.at(-1).attrs?.pageBreakBefore,'Page break undo failed');await app.close();await launch();assert.ok(await page.getByRole('button',{name:'Divided pages',exact:true}).isVisible());await command('redo');await waitFor(async()=>(await recover()).chapters[0].content.content.at(-1).attrs?.pageBreakBefore,'Page break redo failed across restart');await editor.evaluate(element=>{const p=element.querySelector('[data-page-break]');const range=document.createRange();range.selectNodeContents(p);range.collapse(false);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);element.focus();document.dispatchEvent(new Event('selectionchange'))});await page.waitForTimeout(150);await page.keyboard.press('Backspace');await waitFor(async()=>!(await recover()).chapters[0].content.content.at(-1).attrs?.pageBreakBefore,'Backspace did not remove manual break');await command('undo');await waitFor(async()=>(await recover()).chapters[0].content.content.at(-1).attrs?.pageBreakBefore,'Page break removal undo failed');checks.push('Ctrl+Enter creates a saved manual page break, independently undoable and redoable across restart.');
  await editor.click();await page.keyboard.press('Control+Home');await select('uppåtvindar');await page.keyboard.press('Tab');await page.getByRole('listbox',{name:'Rephrasing alternatives'}).waitFor();assert.equal(await page.getByRole('option',{name:/updrafts/}).getAttribute('aria-selected'),'true');assert.equal(await page.getByRole('listbox',{name:'Rephrasing alternatives'}).getByRole('option').count(),3);assert.ok(!JSON.stringify(await recover()).includes('updrafts'));await page.screenshot({path:path.join(output,'v05-rephrase-options.png')});
  await page.keyboard.press('ArrowDown');assert.equal(await page.getByRole('option',{name:/rising air currents/}).getAttribute('aria-selected'),'true');await page.keyboard.press('Enter');await waitFor(async()=>JSON.stringify(await recover()).includes('rising air currents'),'Enter did not accept selected alternative');saved=await recover();assert.equal(saved.chapters[0].content.content[0].content.map(x=>x.text||'').join(''),sentence.replace('uppåtvindar','rising air currents'));await command('undo');await waitFor(async()=>JSON.stringify(await recover()).includes('uppåtvindar'),'Translation undo failed');checks.push('Selection-Tab offers three rated translations; arrow keys and Enter accept only the chosen selection as one undo action.');
  await select('uppåtvindar');await page.keyboard.press('Tab');await page.getByRole('listbox',{name:'Rephrasing alternatives'}).waitFor();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.getSelection().toString()),'uppåtvindar');await page.getByRole('listbox',{name:'Rephrasing alternatives'}).waitFor({state:'hidden'});await page.keyboard.press('Tab');await page.getByRole('listbox',{name:'Rephrasing alternatives'}).waitFor();await page.keyboard.press('Tab');await waitFor(async()=>JSON.stringify(await recover()).includes('updrafts'),'Tab acceptance failed');checks.push('Escape restores the original selection; Tab can request a new list and accept its highlighted option.');
  assert.ok(requests[0].messages.some(x=>x.content.includes('uppåtvindar')&&x.content.includes('sv-SE')));assert.deepEqual(errors,[]);const report={passed:true,checks,flow,userData};await fs.writeFile(path.join(output,'v05-app-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }catch(error){await page?.screenshot({path:path.join(output,'v05-failure.png')}).catch(()=>{});console.error('Renderer errors',errors);throw error}finally{await app?.close().catch(()=>{});await new Promise(resolve=>server.close(resolve))}
})().catch(error=>{console.error(error);process.exitCode=1});
