Add-Type -AssemblyName System.Drawing
$assetDirectory = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\assets'))
[System.IO.Directory]::CreateDirectory($assetDirectory) | Out-Null
$bitmap = [System.Drawing.Bitmap]::new(256, 256)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$green = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#345b4b'))
$paper = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#f8f6ee'))
$gold = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#d9bc80'))
$graphics.Clear([System.Drawing.Color]::Transparent)
$tile = [System.Drawing.Drawing2D.GraphicsPath]::new()
$tile.AddArc(0, 0, 104, 104, 180, 90)
$tile.AddArc(152, 0, 104, 104, 270, 90)
$tile.AddArc(152, 152, 104, 104, 0, 90)
$tile.AddArc(0, 152, 104, 104, 90, 90)
$tile.CloseFigure()
$graphics.FillPath($green, $tile)
$feather = [System.Drawing.Drawing2D.GraphicsPath]::new()
$feather.AddBezier(69, 183, 74, 91, 133, 49, 194, 49)
$feather.AddBezier(194, 49, 197, 112, 157, 170, 88, 187)
$feather.AddLine(88, 187, 130, 122)
$feather.CloseFigure()
$graphics.FillPath($paper, $feather)
$stem = [System.Drawing.Pen]::new($paper, 10)
$stem.StartCap = $stem.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
$graphics.DrawLine($stem, 64, 199, 162, 94)
$vein = [System.Drawing.Pen]::new($green, 7)
$vein.StartCap = $vein.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
$graphics.DrawLine($vein, 93, 168, 113, 117)
$graphics.DrawLine($vein, 114, 146, 159, 131)
$graphics.FillEllipse($gold, 188, 190, 16, 16)
$pngPath = Join-Path $assetDirectory 'icon.png'
$bitmap.Save($pngPath, [System.Drawing.Imaging.ImageFormat]::Png)
$png = [System.IO.File]::ReadAllBytes($pngPath)
$stream = [System.IO.File]::Create((Join-Path $assetDirectory 'icon.ico'))
$writer = [System.IO.BinaryWriter]::new($stream)
$writer.Write([uint16]0); $writer.Write([uint16]1); $writer.Write([uint16]1)
$writer.Write([byte]0); $writer.Write([byte]0); $writer.Write([byte]0); $writer.Write([byte]0)
$writer.Write([uint16]1); $writer.Write([uint16]32)
$writer.Write([uint32]$png.Length); $writer.Write([uint32]22); $writer.Write($png)
$writer.Dispose(); $stream.Dispose()
$stem.Dispose(); $vein.Dispose(); $green.Dispose(); $paper.Dispose(); $gold.Dispose()
$tile.Dispose(); $feather.Dispose(); $graphics.Dispose(); $bitmap.Dispose()
Write-Output 'Created WRAITER application icon.'
