import React, { useState } from 'react';
import { Download } from 'lucide-react';
const formats = [ ['docx', 'Word document (.docx)'], ['odt', 'OpenDocument Text (.odt)'], ['pdf', 'PDF · print / standard'], ['pdf-desktop', 'PDF · desktop reading'], ['pdf-mobile', 'PDF · mobile reading'], ['epub', 'EPUB ebook'], ['txt', 'Plain text (.txt)'], ['bbcode', 'BBCode text (.txt)'], ['md', 'Markdown (.md)'], ['html', 'HTML document (.html)'] ];
export default function ExportDialog({ Modal, project, chapterId, hasSelection, onExport, onClose }) {
  const [format, setFormat] = useState('pdf'), [scope, setScope] = useState('manuscript'), [chapter, setChapter] = useState(chapterId), [colorMode, setColorMode] = useState('light'), [includeTitle, setIncludeTitle] = useState(true), [includeChapterTitles, setIncludeChapterTitles] = useState(true), [working, setWorking] = useState(false);
  const pdf = format.startsWith('pdf');
  async function run() { setWorking(true); try { await onExport(pdf ? 'pdf' : format, { scope, chapterId: chapter, pdfPreset: format === 'pdf-mobile' ? 'mobile' : format === 'pdf-desktop' ? 'desktop' : 'standard', colorMode, includeTitle: scope === 'manuscript' && includeTitle, includeChapterTitles: scope !== 'selection' && includeChapterTitles }); } finally { setWorking(false); } }
  return <Modal title="Export document" onClose={onClose} wide><div className="export-settings"><div className="form-grid"><label>What to export<select className="field-input" aria-label="Export scope" value={scope} onChange={event => setScope(event.target.value)}><option value="manuscript">Full manuscript</option><option value="chapter">One chapter</option><option value="selection" disabled={!hasSelection}>Selected text</option></select></label><label>Format<select className="field-input" aria-label="Export format" value={format} onChange={event => setFormat(event.target.value)}>{formats.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>{scope === 'chapter' && <label>Chapter<select className="field-input" aria-label="Export chapter" value={chapter} onChange={event => setChapter(event.target.value)}>{project.chapters.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}{pdf && <label>Page colour<select className="field-input" aria-label="PDF colour" value={colorMode} onChange={event => setColorMode(event.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></label>}</div><div className="export-options">{scope === 'manuscript' && <label className="check-label"><input type="checkbox" checked={includeTitle} onChange={event => setIncludeTitle(event.target.checked)} />Include manuscript title</label>}{scope !== 'selection' && <label className="check-label"><input type="checkbox" checked={includeChapterTitles} onChange={event => setIncludeChapterTitles(event.target.checked)} />Include chapter headings</label>}</div><p className="small-muted">{format === 'pdf-mobile' ? 'A narrow portrait page with larger relative text for phone reading.' : format === 'pdf-desktop' ? 'A readable screen layout with a comfortable line width.' : format === 'epub' ? 'Reflowable text with chapter navigation, suitable for ebook readers.' : 'The export contains document content and formatting supported by this format.'} Private notes, AI context and editing history are excluded.</p></div><div className="modal-footer"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={working} onClick={run}><Download size={14} />{working ? 'Exporting…' : 'Export'}</button></div></Modal>;
}
