import React, { useEffect, useRef, useState } from 'react';
import { Download, FolderOpen, LoaderCircle, Play, RefreshCw, Square, Upload } from 'lucide-react';

const api = window.wraiter;
const bytes = value => !Number.isFinite(value) ? 'Unknown size' : value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(1)} GB` : `${Math.ceil(value / 1024 ** 2)} MB`;
const errorText = error => String(error?.message || error).replace(/^Error invoking remote method '[^']+': (Error: )?/, '');
const TASKS = [['continue', 'Autocomplete'], ['correct', 'Spell correction'], ['rewrite', 'Rephrase / translate'], ['chat', 'Project assistant'], ['all', 'All AI tasks']];

export default function LocalModels({ onAssign, notify }) {
  const [status, setStatus] = useState(null), [error, setError] = useState(''), [pending, setPending] = useState(''), [progress, setProgress] = useState(null);
  const [section, setSection] = useState('installed'), [task, setTask] = useState('continue'), [search, setSearch] = useState('');
  const [resources, setResources] = useState(null), [flavor, setFlavor] = useState('standard'), [release, setRelease] = useState(null);
  const [modelName, setModelName] = useState('qwen3:0.6b'), [download, setDownload] = useState(null), [source, setSource] = useState(null), [importName, setImportName] = useState('');
  const alive = useRef(true), lastConfig = useRef('');
  const refresh = async () => { const value = await api.localStatus(); if (alive.current) { setStatus(value); setProgress(value.progress); const signature = JSON.stringify(value.config); if (lastConfig.current !== signature) { lastConfig.current = signature; setResources(value.config); } } return value; };
  useEffect(() => {
    alive.current = true; refresh().catch(error => setError(errorText(error)));
    const remove = api.onLocalProgress(value => { if (alive.current) setProgress(value); });
    return () => { alive.current = false; remove(); };
  }, []);
  useEffect(() => { if (!status?.running && !status?.busy) return; const timer = setInterval(() => refresh().catch(() => {}), 3000); return () => clearInterval(timer); }, [status?.running, status?.busy]);
  async function run(label, action, { reload = true } = {}) {
    if (pending) return; setPending(label); setError('');
    try { const result = await action(); if (reload) await refresh(); return result; }
    catch (error) { if (alive.current) setError(errorText(error)); }
    finally { if (alive.current) setPending(''); }
  }
  const working = Boolean(pending || status?.busy);
  const fraction = progress?.total > 0 ? Math.max(0, Math.min(100, 100 * (progress.completed || 0) / progress.total)) : null;
  const assign = name => { for (const [key] of TASKS) if (key !== 'all' && (task === 'all' || task === key)) onAssign(key, name); notify(`${name} assigned to ${TASKS.find(([key]) => key === task)[1]}. Save settings to keep this choice.`); };

  if (!status) return <div className="local-models"><p role="status">{error || 'Discovering local engines and models…'}</p>{error && <button className="secondary-button" onClick={() => run('refresh', refresh)}>Try again</button>}</div>;
  return <div className="local-models">
    <div className="local-heading"><div><h3>Local models</h3><p className="small-muted">Run downloaded models on this computer. WRAITER starts and stops its own hidden engine.</p></div><button className="secondary-button" disabled={working} onClick={() => run('refresh', refresh)} aria-label="Refresh local models"><RefreshCw size={14} /></button></div>
    <div className="local-runtime-row"><span className={'tiny-dot ' + (status.running ? 'running' : '')} /><strong>{status.running ? 'Engine running' : status.runtime.available ? 'Engine ready to start' : 'Engine setup needed'}</strong><span className="small-muted">{status.runtime.source === 'portable' ? `Portable Ollama ${status.runtime.portable.version}` : status.runtime.source === 'installed' ? 'Using installed Ollama' : 'No engine selected'}</span><button className="secondary-button" disabled={working || !status.runtime.available} onClick={() => run('engine', () => status.running ? api.stopLocal() : api.startLocal())}>{status.running ? <Square size={13} /> : <Play size={13} />}{status.running ? 'Stop engine' : 'Start engine'}</button></div>
    {(progress || pending) && <div className={'local-progress ' + (progress?.phase === 'error' ? 'error' : '')} role="status"><div>{pending && <LoaderCircle size={14} className="spin" />}<span>{progress?.message || 'Working…'}</span>{status.busy || ['install', 'pull', 'import'].includes(pending) ? <button className="text-button" onClick={() => api.cancelLocal().then(() => refresh()).catch(error => setError(errorText(error)))}>Cancel operation</button> : null}</div>{fraction != null && working && <><progress aria-label="Local model progress" value={fraction} max="100" /><small>{bytes(progress.completed || 0)} / {bytes(progress.total)}</small></>}</div>}
    {(error || status.error) && <p className="ai-error" role="alert">{error || status.error}</p>}
    <details className="local-setup"><summary>Engine and model storage</summary>
      <label>Engine<select className="field-input" aria-label="Local engine source" disabled={working} value={status.config.runtimeMode} onChange={event => run('configure', () => api.configureLocal({ runtimeMode: event.target.value }))}><option value="auto">Automatic — portable, then installed</option><option value="portable">WRAITER portable engine</option><option value="installed">Installed Ollama engine</option></select></label>
      <div className="local-download-engine"><label>Portable package<select className="field-input" aria-label="Portable engine package" value={flavor} disabled={working} onChange={event => { setFlavor(event.target.value); setRelease(null); }}><option value="standard">Standard — NVIDIA / CPU</option><option value="amd">Standard + AMD ROCm libraries</option></select></label><button className="secondary-button" disabled={working} onClick={() => run('release', async () => { const value = await api.localRelease(flavor); if (alive.current) setRelease(value); }, { reload: false })}>Check engine download</button>{release && <button className="primary-button" disabled={working} onClick={() => run('install', () => api.installLocal(flavor))}><Download size={14} />Install {release.version} ({bytes(release.bytes)})</button>}</div>
      <p className="small-muted">Downloaded from Ollama’s official release, with SHA-256 verification. The engine is separate from your models and can be used without installing the Ollama desktop app.</p>
      <label>Model folder<input className="field-input" aria-label="Local model folder" readOnly value={status.modelDirectory} /></label>
      <div className="local-buttons"><button className="secondary-button" disabled={working} onClick={() => run('folder', () => api.localFolder('detected'))}>Use detected Ollama folder</button><button className="secondary-button" disabled={working} onClick={() => run('folder', () => api.localFolder('wraiter'))}>Use WRAITER folder</button><button className="secondary-button" disabled={working} onClick={() => run('folder', () => api.localFolder('browse'))}><FolderOpen size={14} />Choose folder</button></div>
      <p className="small-muted">Existing models are discovered without starting Ollama or copying their files. Downloads and GGUF imports go into the selected folder. Changing folders does not move or delete models.</p>
    </details>
    <details className="local-setup"><summary>Memory and acceleration</summary><p className="small-muted">{bytes(status.hardware.freeRam)} RAM free of {bytes(status.hardware.ram)}. {status.hardware.gpus.map(gpu => `${gpu.name} · ${bytes(gpu.memory)} VRAM`).join('; ') || status.hardware.adapterNames?.join(', ') || 'Automatic GPU detection is available when the engine starts.'}</p>
      <div className="form-grid"><label>Acceleration<select className="field-input" aria-label="Local acceleration" value={resources.gpu} disabled={working} onChange={event => setResources({ ...resources, gpu: event.target.value })}><option value="auto">Automatic GPU selection</option><option value="cpu">CPU only</option>{status.hardware.gpus.map(gpu => <option key={gpu.id} value={gpu.id}>{gpu.name}</option>)}</select></label><label>Context size (tokens)<select className="field-input" aria-label="Local context size" value={resources.contextLength} onChange={event => setResources({ ...resources, contextLength: Number(event.target.value) })}>{[2048,4096,8192,16384,32768,65536,131072].map(value => <option key={value} value={value}>{value.toLocaleString()}</option>)}</select></label><label>Unload after idle<select className="field-input" aria-label="Local unload delay" value={resources.idleMinutes} onChange={event => setResources({ ...resources, idleMinutes: Number(event.target.value) })}>{[[0,'Immediately'],[1,'1 minute'],[5,'5 minutes'],[15,'15 minutes'],[30,'30 minutes'],[60,'1 hour'],[120,'2 hours']].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Models kept loaded<select className="field-input" aria-label="Local loaded model limit" value={resources.maxLoaded} onChange={event => setResources({ ...resources, maxLoaded: Number(event.target.value) })}><option value="1">1 — lowest memory use</option><option value="2">2 — faster task switching</option><option value="3">3 — requires more memory</option></select></label></div>
      <p className="small-muted">Larger contexts and multiple loaded models use more memory. Model file size is a lower bound; working memory and context add overhead. Small models may be less reliable at agent actions.</p><button className="secondary-button" disabled={working} onClick={() => run('configure', () => api.configureLocal({ gpu: resources.gpu, contextLength: resources.contextLength, idleMinutes: resources.idleMinutes, maxLoaded: resources.maxLoaded }))}>Apply resource settings</button>
    </details>
    <div className="local-library-tabs" role="tablist" aria-label="Local model library"><button role="tab" aria-selected={section === 'installed'} onClick={() => setSection('installed')}>On this computer ({status.models.length})</button><button role="tab" aria-selected={section === 'download'} onClick={() => setSection('download')}>Download models</button><button role="tab" aria-selected={section === 'file'} onClick={() => setSection('file')}>Add GGUF file</button></div>
    {section === 'installed' && <><div className="local-library-controls"><input className="field-input" aria-label="Search local models" placeholder="Find a downloaded model" value={search} onChange={event => setSearch(event.target.value)} /><label>Use for<select className="field-input" aria-label="Local model task" value={task} onChange={event => setTask(event.target.value)}>{TASKS.map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><div className="local-model-list">{status.models.filter(model => model.name.toLowerCase().includes(search.toLowerCase())).map(model => {
      const loaded = status.loaded.find(item => item.name === model.name || item.model === model.name);
      return <div className="local-model-row" key={model.name}><div><strong>{model.name}</strong><small>{bytes(model.size)} on disk · {model.complete ? loaded ? `Loaded · ${bytes(loaded.size_vram || 0)} GPU memory` : 'Downloaded' : 'Missing model data — download incomplete'}</small></div>{loaded && <button className="text-button" disabled={working} onClick={() => run('unload', () => api.unloadLocal(model.name))}>Unload</button>}<button className="secondary-button" disabled={!model.complete || working} onClick={() => assign(model.name)}>Use model</button></div>;
    })}</div>{!status.models.length && <p className="small-muted">No models found in this folder. Choose your Ollama model folder, add a GGUF file, or download a model.</p>}{status.warnings.map(warning => <p key={warning} className="small-muted">{warning}</p>)}</>}
    {section === 'download' && <><p className="small-muted">Choose a starting model or enter any public Ollama model name. Check its download size before downloading. Model availability and compatibility depend on the engine version.</p><select className="field-input" aria-label="Model download catalog" value={status.catalog.some(item => item.name === modelName) ? modelName : ''} onChange={event => { setModelName(event.target.value); setDownload(null); }}><option value="" disabled>Custom model</option>{status.catalog.map(item => <option key={item.name} value={item.name}>{item.label} — {item.description}</option>)}</select><div className="input-with-button"><input className="field-input" aria-label="Model to download" value={modelName} onChange={event => { setModelName(event.target.value); setDownload(null); }} /><button className="secondary-button" disabled={working || !modelName.trim()} onClick={() => run('catalog', async () => { const value = await api.localCatalogInfo(modelName); if (alive.current) setDownload(value); }, { reload: false })}>Check download</button></div>{download && <div className="local-download-info"><span>{download.name} · {bytes(download.bytes)} download</span><button className="primary-button" disabled={working || !status.runtime.available} onClick={() => run('pull', async () => { await api.pullLocal(download.name); setSection('installed'); })}><Download size={14} />Download model</button></div>}{!status.runtime.available && <p className="small-muted">Set up the engine above before downloading a model.</p>}</>}
    {section === 'file' && <><p className="small-muted">Add a GGUF v2/v3 model downloaded from a model publisher. The original file is preserved. Registration may copy it into the selected model folder; existing identical blobs are reused.</p><button className="secondary-button" disabled={working} onClick={() => run('choose', async () => { const value = await api.chooseGGUF(); if (value) { setSource(value); setImportName(value.name.replace(/\.gguf$/i, '').toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^[^a-z0-9]+/, '').slice(0, 120) || 'my-local-model'); } }, { reload: false })}><FolderOpen size={14} />Choose GGUF file</button>{source && <div className="local-import"><p>{source.name} · {bytes(source.bytes)}</p><label>Model name<input className="field-input" aria-label="Imported local model name" value={importName} onChange={event => setImportName(event.target.value)} /></label><button className="primary-button" disabled={working || !importName.trim() || !status.runtime.available} onClick={() => run('import', async () => { await api.importGGUF(source.token, importName); setSource(null); setSection('installed'); })}><Upload size={14} />Add model</button></div>}</>}
    <p className="small-muted local-footnote">Engine, storage and resource changes apply immediately. Task assignments are saved with Save settings. Models stay on disk when WRAITER closes.</p>
  </div>;
}
