import React, { useRef, useState } from 'react';
const api = window.wraiter;
const cleanError = error => String(error?.message || error).replace(/^Error invoking remote method '[^']+': (Error: )?/, '');
const tasks = ['continue', 'correct', 'rewrite', 'chat'];

export function SetupWizard({ prefs, updatePrefs, Modal, onClose, onTutorial }) {
  const [step, setStep] = useState(0), [mode, setMode] = useState(prefs.setupMode || 'simple');
  const [provider, setProvider] = useState(prefs.provider === 'claude' ? 'claude' : 'codex');
  const [executable, setExecutable] = useState(''), [model, setModel] = useState(''), [continuous, setContinuous] = useState(false);
  const [status, setStatus] = useState(null), [ready, setReady] = useState(false), [busy, setBusy] = useState(''), [message, setMessage] = useState(''), [error, setError] = useState('');
  const busyRef = useRef(false);
  const name = provider === 'codex' ? 'Codex' : 'Claude Code';
  const profile = { provider, baseUrl: '', model, codexPath: provider === 'codex' ? executable : '', claudePath: provider === 'claude' ? executable : '' };
  const titles = ['Welcome to WRAITER', 'Choose your writing AI', 'Connect your account', 'Try your connection', 'Ready to write'];
  async function perform(label, fn) {
    if (busyRef.current) return;
    busyRef.current = true; setBusy(label); setError('');
    try { await fn(); } catch (error) { setError(cleanError(error)); } finally { busyRef.current = false; setBusy(''); }
  }
  const close = () => { if (!busyRef.current) onClose(); };
  async function check() { setReady(false); const result = await api.connectProvider(profile); setStatus(result); setMessage(result.message); }
  async function finish() {
    if (!ready) return;
    await updatePrefs({ ...profile, taskProfiles: Object.fromEntries(tasks.map(task => [task, profile])), enabled: true, continuous, setupMode: mode, setupComplete: true });
    onTutorial();
  }
  function invalidate() { setReady(false); setStatus(null); setMessage(''); setError(''); }
  return <Modal title={titles[step]} subtitle={`Setup · Step ${step + 1} of ${titles.length}`} onClose={close} wide>
    <div className="onboarding-progress" aria-label={`Step ${step + 1} of ${titles.length}`}>{titles.map((title, index) => <span key={title} className={index <= step ? 'done' : ''} />)}</div>
    <div className="onboarding-body">
      {step === 0 && <><p className="onboarding-lead">Your words. A little help when you want it.</p><p>We’ll help you connect an AI account, check that it works, and learn your way around. You don’t need to know any commands.</p><div className="setup-choices">{[['simple', 'Simple · recommended', 'Choose an AI account. We take care of the writing settings.'], ['advanced', 'Advanced', 'Choose a helper location, model and automatic suggestions.']].map(([value, label, detail]) => <button key={value} aria-pressed={mode === value} className={mode === value ? 'selected' : ''} onClick={() => { setMode(value); if (value === 'simple') { setExecutable(''); setModel(''); setContinuous(false); invalidate(); } }}><strong>{label}</strong><span>{detail}</span></button>)}</div><aside className="onboarding-tip">Already installed WRAITER? This guide connects your AI. The Windows installer lets you choose where WRAITER itself is stored.</aside></>}
      {step === 1 && <><p>Choose the account you want to use for writing help.</p><div className="setup-choices">{[['codex', 'Codex', 'Use your ChatGPT / Codex account.'], ['claude', 'Claude Code', 'Use your Claude Code account.']].map(([value, label, detail]) => <button key={value} aria-pressed={provider === value} className={provider === value ? 'selected' : ''} onClick={() => { setProvider(value); setExecutable(''); setModel(''); invalidate(); }}><strong>{label}</strong><span>{detail}</span></button>)}</div><aside className="onboarding-tip"><strong>What is a helper?</strong><p>It connects WRAITER to your AI account in the background. WRAITER uses the account saved by that helper. Your provider’s account access and usage limits apply; installing WRAITER does not include a subscription.</p></aside></>}
      {step === 2 && <><h3>Let’s connect {name}</h3><p>First, check for an existing installation and saved account. If the helper is missing, use Install. Then sign in and check again.</p><div className="button-grid"><button disabled={!!busy} className="primary-button" onClick={() => perform('Checking your account…', check)}>Check my account</button><button disabled={!!busy} className="secondary-button" onClick={() => perform(`Installing ${name}… This may take several minutes.`, async () => { setReady(false); setStatus(null); const result = await api.setupInstall(provider); setMessage(result.message); })}>Install {name}</button><button disabled={!!busy} className="secondary-button" onClick={() => perform('Opening sign-in…', async () => { setReady(false); const result = await (provider === 'codex' ? api.loginProvider(profile) : api.setupClaudeLogin(profile)); setMessage(result.message || 'Complete browser sign-in, then check your account again.'); })}>Sign in</button></div><aside className="onboarding-tip">Install downloads and runs the official {name} installer for your Windows account. Internet access is needed. Sign-in may open your browser{provider === 'claude' ? ' and a one-time sign-in window' : ''}. Finish there, return here, and choose “Check my account”.</aside><button className="text-button" disabled={!!busy} onClick={() => perform('Opening help…', () => api.setupHelp(provider))}>Open official installation help</button>
        {mode === 'advanced' && <div className="settings-section"><label>Helper executable (optional)<div className="input-with-button"><input aria-label="Helper executable" className="field-input" value={executable} placeholder="Find automatically" onChange={e => { setExecutable(e.target.value); invalidate(); }} disabled={!!busy} /><button disabled={!!busy} className="secondary-button" onClick={() => perform('Choosing helper…', async () => { const chosen = await api.setupChoose(provider); if (chosen) { setExecutable(chosen); invalidate(); } })}>Browse</button></div></label></div>}</>}
      {step === 3 && <><h3>A small writing test</h3><p>We’ll ask {name} to finish “The morning sun”. This uses a small amount of your provider allowance. Your manuscript is not included in this test.</p>
        {mode === 'advanced' && <div className="settings-section"><label>Model (optional)<input className="field-input" aria-label="Setup model" list="setup-models" value={model} disabled={!!busy} placeholder="Use the provider default" onChange={e => { setModel(e.target.value); setReady(false); }} /></label><datalist id="setup-models">{status?.models?.map(value => <option key={value} value={value} />)}</datalist><label className="check-label"><input type="checkbox" checked={continuous} onChange={e => setContinuous(e.target.checked)} />Offer suggestions automatically while I write</label></div>}
        <button className="primary-button" disabled={!!busy} onClick={() => perform('Testing writing assistance…', async () => { setReady(false); const result = await api.setupTest(profile); setReady(result.ready === true); setMessage(`${result.message}\nSample: ${result.sample}`); })}>Run writing test</button><aside className="onboarding-tip">When you use AI, relevant writing and enabled reference files go to your chosen provider. Private notes are excluded. Simple setup starts with suggestions on request, so you decide when to ask.</aside></>}
      {step === 4 && <><p className="onboarding-lead">Your connection passed its writing test.</p><p>Choose “Save and start tutorial” to use {name} for suggestions, corrections, rephrasing and the writing assistant.</p><aside className="onboarding-tip">You can change providers or assign different models later in Settings → AI connections. Reopen this guide anytime from Help → Set up AI.</aside></>}
      {message && <p className="connection-status" role="status" style={{ whiteSpace: 'pre-wrap' }}>{message}</p>}
      {busy && <p role="status">{busy}</p>}{error && <p className="connection-status error" role="alert">{error}</p>}
    </div>
    <div className="modal-footer"><button className="text-button" disabled={!!busy} onClick={() => perform('Saving…', async () => { await updatePrefs({ setupComplete: true, setupMode: mode }); onTutorial(); })}>Set up later</button>{busy && <button className="secondary-button" onClick={() => api.setupCancel().catch(e => setError(cleanError(e)))}>Cancel operation</button>}<button className="secondary-button" disabled={!!busy || step === 0} onClick={() => setStep(step - 1)}>Back</button>{step < 4 ? <button className="primary-button" disabled={!!busy || (step === 2 && (!status?.connected || status.needsLogin)) || (step === 3 && !ready)} onClick={() => { setMessage(''); setError(''); setStep(step + 1); }}>Next</button> : <button className="primary-button" disabled={!!busy || !ready} onClick={() => perform('Saving your connection…', finish)}>Save and start tutorial</button>}</div>
  </Modal>;
}
